DROP TABLE IF EXISTS person, person1, person2, person3, person4, "order", item, album, book;

-- DROP DATABASE IF EXISTS project1;
-- CREATE DATABASE project1;

-- PRIMARY KEY - UNIQUE and NOT NULL
CREATE TABLE IF NOT EXISTS person
(
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(30)  NOT NULL,
    age   INTEGER CHECK (age >= 0 AND age <= 120) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    address  VARCHAR(100)  NOT NULL
    );

INSERT INTO person (name, age, email, address)
VALUES ('Иван Иванов', 25, 'ivan@example.com', 'Russia, Москва, 123456');

INSERT INTO person (name, age, email, address)
VALUES ('Анна Петрова', 32, 'anna@example.com', 'Russia, Санкт-Петербург, 123456');

INSERT INTO person (name, age, email, address)
VALUES ('Сергей Коваленко', 41, 'ser,gey@example.com', 'Ukraine, Киев, 222222');

CREATE TABLE IF NOT EXISTS book (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL ,
    year INT check ( year > 1900 )  NOT NULL,
    person_id BIGINT REFERENCES person(person_id) ON DELETE SET NULL
);

INSERT INTO book (title, author, year, person_id) VALUES ('java', 'hortsman', 2020, 1);
INSERT INTO book (title, author, year, person_id) values ('frontend', 'prokopenko', 2025, null);

-- CREATE TABLE IF NOT EXISTS "order" (
--     order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     person_id BIGINT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
--     item_name VARCHAR(30)
-- );
--
-- CREATE TABLE IF NOT EXISTS item (
--     item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     item_name VARCHAR(50) UNIQUE NOT NULL,
--     price DOUBLE PRECISION NOT NULL,
--     description VARCHAR(500)
-- )

