DROP TABLE IF EXISTS person_library, library, person, book, book_copy;

CREATE TABLE IF NOT EXISTS person
(
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_media_id varchar(300) NOT NULL UNIQUE,
    name      VARCHAR(30)  NOT NULL,
    age       INTEGER CHECK (age >= 0 AND age <= 120) NOT NULL,
    email     VARCHAR(255) UNIQUE NOT NULL,
    password  VARCHAR(500) NOT NULL,
    address   VARCHAR(100)  NOT NULL
);

INSERT INTO person (person_media_id, name, age, email, password, address)
VALUES
    ('EDC00000001', 'Иван Иванов', 25, 'ivan@example.com', '123', 'Ukraine, Odessa, 123456'),
    ('EDC00000002', 'Анастасия Бартовщук', 32, 'ayabarto@example.com', '123', 'Russia, Санкт-Петербург, 123456'),
    ('EDC00000003', 'Сергей Коваленко', 41, 'sergey@example.com', '123', 'Ukraine, Kiev, 222222'),
    ('EDC00000004', 'Анна Петрова', 88, 'anna@example.com', '123', 'Ukraine, Kiev, 222222');

CREATE TABLE IF NOT EXISTS book
(
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(100) NOT NULL,
    author  VARCHAR(100) NOT NULL,
    year    INT CHECK (year > 1900) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO book (title, author, year)
VALUES
    ('Основы java', 'Hortsman', 2020),
    ('Java Script для детей', 'Prokopenko', 2025);


CREATE TABLE IF NOT EXISTS book_copy
(
    copy_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT REFERENCES book(book_id) ON DELETE CASCADE,
    person_id  BIGINT REFERENCES person(person_id) ON DELETE SET NULL,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO book_copy (book_id, person_id, is_available)
VALUES
    (1, NULL, TRUE),
    (1, 2, TRUE),
    (2, NULL, TRUE);

CREATE INDEX IF NOT EXISTS idx_book_copy_book_id ON book_copy(book_id);
CREATE INDEX IF NOT EXISTS idx_book_copy_person_id ON book_copy(person_id);

CREATE TABLE IF NOT EXISTS library
(
    library_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL
);

-- Данные библиотек
INSERT INTO library (name, address)
VALUES
    ('Библиотека 1  Киев Голосеевский район ', 'Ukraine, Kyiv, 123456'),
    ('Библиотека 2 Киев Троещина', 'Ukraine, Kiev, 654321'),
    ('Библиотека 3 Бровары', 'Ukraine, Brovary, 654321');

-- Промежуточная таблица person_library (ManyToMany)
CREATE TABLE IF NOT EXISTS person_library
(
    person_id  BIGINT REFERENCES person(person_id) ON DELETE CASCADE,
    library_id BIGINT REFERENCES library(library_id) ON DELETE CASCADE,
    PRIMARY KEY (person_id, library_id)
);

INSERT INTO person_library (person_id, library_id)
VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 1),
    (4, 2),
    (4, 3);